const M={view:'cockpit',profile:localStorage.getItem('nmcp.matrix.profile')||'enterprise',token:localStorage.getItem('nmcp.admin.token')||sessionStorage.getItem('nmcp.admin.token')||'',policy:null,doctor:null,runtime:null,audit:{events:[]},catalog:{servers:[]},summary:null,decisions:{decisions:[]},upstreams:{upstreams:[]},health:false,ready:false,query:''};
const fallback={roots:[],checks:[],events:[],servers:[]};
function $(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function n(v){const x=Number(v);return Number.isFinite(x)?x:0}
function apiOpts(){const h={};if(M.token)h['x-nmcp-admin-token']=M.token;return{headers:h}}
async function j(url){const r=await fetch(url,apiOpts());const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||b.error||r.statusText);return b}
async function safe(p,alt){try{return await p}catch(e){return alt}}
function kind(ok,warn=false){return ok?'ok':warn?'warn':'bad'}
function riskKind(v){const s=String(v||'').toLowerCase();if(s.includes('high')||s.includes('quarantine'))return'bad';if(s.includes('elevated')||s.includes('medium')||s.includes('approval'))return'warn';if(s.includes('standard')||s.includes('low'))return'ok';return'info'}
function dot(k){return `<span class="om-dot ${k}"></span>`}
function pill(a,b,k){return `<span class="om-pill">${dot(k)}<span>${esc(a)}</span><strong>${esc(b)}</strong></span>`}
function tag(v,k='info'){return `<span class="om-tag ${k}">${esc(v)}</span>`}
function toast(msg){const el=document.createElement('div');el.className='om-toast';el.textContent=msg;$('matrix-toasts').appendChild(el);setTimeout(()=>el.remove(),2800)}
function shortPath(p){return String(p||'').replace(/^\\\\\?\\/,'')}
function fmtTime(v){if(!v)return'-';const d=new Date(v);return isNaN(d.getTime())?String(v):d.toLocaleTimeString()}
function setMatrixProfile(profile){M.profile=profile;localStorage.setItem('nmcp.matrix.profile',profile);render()}
function matrixNav(view){M.view=view;render()}
function clock(){const d=new Date();$('matrix-clock').textContent='UTC '+d.toISOString().slice(11,19)}setInterval(clock,1000);clock();
async function loadMatrix(){const h=await safe(fetch('/healthz').then(r=>({ok:r.ok})),{ok:false});const r=await safe(fetch('/readyz').then(r=>({ok:r.ok})),{ok:false});M.health=!!h.ok;M.ready=!!r.ok;const items=await Promise.all([safe(j('/api/policy'),null),safe(j('/api/doctor'),null),safe(j('/api/diagnostics/runtime'),null),safe(j('/api/audit/recent?limit=100'),{events:[]}),safe(j('/api/gateway/catalog'),{servers:[]}),safe(j('/api/gateway/catalog/summary'),null),safe(j('/api/gateway/decisions/export'),{decisions:[]}),safe(j('/api/upstreams'),{upstreams:[]})]);[M.policy,M.doctor,M.runtime,M.audit,M.catalog,M.summary,M.decisions,M.upstreams]=items;render()}
function render(){const profile=$('matrix-profile');if(profile)profile.value=M.profile;document.querySelectorAll('.om-nav-item[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===M.view));$('matrix-title').textContent={cockpit:'OPERATOR MATRIX',sessions:'SESSIONS & STREAMS',policy:'POLICY MATRIX',gateway:'MCP GATEWAY STORE',execution:'EXECUTION CONSOLE',audit:'LIVE AUDIT TAPE',diagnostics:'DIAGNOSTICS'}[M.view]||'OPERATOR MATRIX';renderPills();if(M.view==='sessions')renderSessions();else if(M.view==='policy')renderPolicy();else if(M.view==='gateway')renderGateway();else if(M.view==='execution')renderExecution();else if(M.view==='audit')renderAudit();else if(M.view==='diagnostics')renderDiagnostics();else renderCockpit();renderContext()}
function roots(){return (M.policy&&M.policy.roots)||fallback.roots}
function events(){return (M.audit&&M.audit.events)||fallback.events}
function checks(){return (M.doctor&&M.doctor.checks)||fallback.checks}
function transport(){return (M.runtime&&M.runtime.transport)||{}}
function catalogServers(){return ((M.catalog&&M.catalog.servers)||[]).map(s=>({id:s.id||'',name:s.display_name||s.label||s.name||s.id||'MCP Server',publisher:s.publisher||s.source||'catalog',source:s.source_type||s.source||'catalog',risk:s.risk_tier||s.risk||'standard',mode:s.default_mode||'metadata_only',profiles:s.profiles||[],domains:s.capability_domains||[],tools:s.tool_count||(s.tools||[]).length||0,secrets:s.required_secrets||[],audit:!!s.audit_required,notes:s.notes||s.description||s.summary||'Governed MCP server catalog entry.'}))}
function decision(id){return ((M.decisions&&M.decisions.decisions)||[]).find(d=>d.id===id)}
function renderPills(){const tr=transport();const enabled=((M.decisions&&M.decisions.decisions)||[]).filter(d=>d.enabled).length;const total=(M.summary&&M.summary.server_count)||catalogServers().length;const streamWarn=n(tr.active_sessions)>1||n(tr.audit_subscribers)>1;$('matrix-pills').innerHTML=[pill('Service',M.health?'Running':'Offline',kind(M.health)),pill('Admin',M.ready?'Ready':'Check',kind(M.ready,true)),pill('MCP',M.ready?'Ready':'Check',kind(M.ready,true)),pill('Streams',streamWarn?'Watch':'Healthy',streamWarn?'warn':'ok'),pill('Policy',M.policy?'Loaded':'Missing',M.policy?'ok':'bad'),pill('Upstreams',enabled+' / '+total+' Enabled',enabled?'info':'warn')].join('')}
function renderCockpit(){const c=checks(),pass=c.filter(x=>x.ok).length,fail=c.length-pass;const ev=events();const deny=ev.filter(e=>String(e.decision||e.summary||'').toLowerCase().includes('deny')).length;const tr=transport();const sessions=n(tr.active_sessions);const enabled=((M.decisions&&M.decisions.decisions)||[]).filter(d=>d.enabled).length;const total=(M.summary&&M.summary.server_count)||catalogServers().length;const posture=deny||fail?'MEDIUM':'LOW';$('matrix-content').innerHTML=`<div class="om-hero"><div class="om-panel"><div class="om-panel-head"><span>Runtime cockpit</span><button class="om-btn" onclick="loadMatrix()">Refresh</button></div><div class="om-hex-stage"><div class="om-hex-wrap"><div class="om-hex ${fail?'warn':'ok'} pos-health"><div class="om-hex-inner"><span class="lbl">Health</span><span class="val">${pass}/${c.length||pass}</span><span class="sub">checks ok</span></div></div><div class="om-hex ${deny?'bad':'ok'} pos-denied"><div class="om-hex-inner"><span class="lbl">Denied</span><span class="val">${deny}</span><span class="sub">loaded sample</span></div></div><div class="om-hex ${sessions>1?'warn':'ok'} pos-sessions"><div class="om-hex-inner"><span class="lbl">Sessions</span><span class="val">${sessions}</span><span class="sub">active</span></div></div><div class="om-hex ${posture==='LOW'?'ok':'warn'} pos-risk"><div class="om-hex-inner"><span class="lbl">Risk posture</span><span class="val">${posture}</span><span class="sub">${esc(M.profile)} view</span></div></div><div class="om-hex cyan pos-audit"><div class="om-hex-inner"><span class="lbl">Audit</span><span class="val">LIVE</span><span class="sub">${ev.length} events</span></div></div><div class="om-hex ${M.policy?'ok':'bad'} pos-policy"><div class="om-hex-inner"><span class="lbl">Policy</span><span class="val">${M.policy?'ACTIVE':'MISS'}</span><span class="sub">${roots().length} roots</span></div></div><div class="om-hex info pos-tools"><div class="om-hex-inner"><span class="lbl">Gateway</span><span class="val">${enabled}/${total}</span><span class="sub">enabled</span></div></div></div></div></div><div class="om-grid cols-2"><div class="om-card"><div class="om-card-label">Service</div><div class="om-card-value ${M.health?'ok':'bad'}">${M.health?'Running':'Offline'}</div><div class="om-card-sub">healthz</div></div><div class="om-card"><div class="om-card-label">Admin</div><div class="om-card-value ${M.ready?'ok':'warn'}">${M.ready?'Ready':'Check'}</div><div class="om-card-sub">readyz</div></div><div class="om-card"><div class="om-card-label">Policy roots</div><div class="om-card-value">${roots().length}</div><div class="om-card-sub">effective policy</div></div><div class="om-card"><div class="om-card-label">Gateway catalog</div><div class="om-card-value info">${total}</div><div class="om-card-sub">MCP servers cataloged</div></div></div></div>`}
function renderSessions(){const tr=transport();const active=Math.max(n(tr.active_sessions),0);const rows=active?Array.from({length:active},(_,i)=>({id:'session_'+String(i+1).padStart(2,'0'),client:i?'Secondary MCP client':'Primary MCP client',status:active>1&&i?'Backpressure watch':'Healthy',rate:i?'0.2':'1.8'})):[];$('matrix-content').innerHTML=`<div class="om-grid cols-4"><div class="om-card"><div class="om-card-label">Active sessions</div><div class="om-card-value ${active>1?'warn':'ok'}">${active}</div></div><div class="om-card"><div class="om-card-label">Audit subscribers</div><div class="om-card-value info">${n(tr.audit_subscribers)}</div></div><div class="om-card"><div class="om-card-label">Max sessions</div><div class="om-card-value">${n(tr.max_sessions)}</div></div><div class="om-card"><div class="om-card-label">Backpressure</div><div class="om-card-value ${active>1?'warn':'ok'}">${active>1?'Watch':'Clear'}</div></div></div><div class="om-panel"><div class="om-panel-head"><span>Sessions & Streams</span>${tag('controls pending backend','warn')}</div><table class="om-table"><thead><tr><th>Session ID</th><th>Client</th><th>Transport</th><th>Msgs/s</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="mono">${esc(r.id)}</td><td>${esc(r.client)}</td><td>streamable-http</td><td class="mono">${esc(r.rate)}</td><td>${tag(r.status,r.status==='Healthy'?'ok':'warn')}</td><td><button class="om-btn" onclick="toast('Drain endpoint pending')">Drain</button> <button class="om-btn danger" onclick="toast('Terminate endpoint pending')">Terminate</button></td></tr>`).join('')||'<tr><td colspan="6" class="muted">No active sessions reported.</td></tr>'}</tbody></table></div>`}
function renderPolicy(){const p=M.policy||{};const r=roots();const nodes=[['Execution Boundary',Object.keys(p.tool_paths||{}).length+' tool paths','warn'],['Roots',r.length+' governed roots','ok'],['Gateway Activation',((M.decisions&&M.decisions.decisions)||[]).length+' decisions','info'],['Audit Settings','jsonl / event log','ok'],['Admin Bind',p.admin_bind||'127.0.0.1:18769','ok'],['MCP Bind',p.mcp_bind||'127.0.0.1:18770','ok'],['Overrides',p.auto_approve?'auto-approve enabled':'restricted',p.auto_approve?'bad':'ok'],['Profiles',Object.keys(p.execution_profiles||{}).length+' execution profiles','info']];$('matrix-content').innerHTML=`<div class="om-grid cols-4"><div class="om-card"><div class="om-card-label">Policy</div><div class="om-card-value ${M.policy?'ok':'bad'}">${M.policy?'Loaded':'Missing'}</div></div><div class="om-card"><div class="om-card-label">Roots</div><div class="om-card-value">${r.length}</div></div><div class="om-card"><div class="om-card-label">Profiles</div><div class="om-card-value info">${Object.keys(p.execution_profiles||{}).length}</div></div><div class="om-card"><div class="om-card-label">Auto approve</div><div class="om-card-value ${p.auto_approve?'bad':'ok'}">${p.auto_approve?'ON':'OFF'}</div></div></div><div class="om-panel"><div class="om-panel-head"><span>Governance topology</span><button class="om-btn" onclick="location.href='/admin'">Classic editor</button></div><div class="om-panel-body"><div class="om-policy-map">${nodes.map(x=>`<div class="om-policy-node"><strong>${esc(x[0])}</strong><span>${esc(x[1])}</span><div style="margin-top:10px">${tag(x[2]==='bad'?'High attention':x[2]==='warn'?'Review':'Active',x[2])}</div></div>`).join('')}</div></div></div><div class="om-panel"><div class="om-panel-head"><span>Effective roots</span></div><table class="om-table"><thead><tr><th>ID</th><th>Path</th><th>Permissions</th></tr></thead><tbody>${r.map(x=>`<tr><td><strong>${esc(x.id)}</strong></td><td class="mono">${esc(shortPath(x.path))}</td><td>${(x.permissions||[]).map(p=>tag(p,p==='git.publish'?'bad':p==='execute'?'warn':'info')).join(' ')}</td></tr>`).join('')||'<tr><td colspan="3" class="muted">No roots configured.</td></tr>'}</tbody></table></div>`}
function renderGateway(){const all=catalogServers();const q=String(M.query||'').toLowerCase();const list=all.filter(s=>!q||JSON.stringify(s).toLowerCase().includes(q));const enabled=((M.decisions&&M.decisions.decisions)||[]).filter(d=>d.enabled).length;$('matrix-content').innerHTML=`<div class="om-panel"><div class="om-panel-head"><span>Gateway Store</span><input class="om-store-search" placeholder="Search MCP servers" value="${esc(M.query)}" oninput="M.query=this.value;renderGateway()"/></div><div class="om-panel-body"><div class="om-grid cols-4" style="margin-bottom:14px"><div class="om-card"><div class="om-card-label">Cataloged</div><div class="om-card-value">${all.length}</div></div><div class="om-card"><div class="om-card-label">Enabled</div><div class="om-card-value info">${enabled}</div></div><div class="om-card"><div class="om-card-label">High risk</div><div class="om-card-value bad">${all.filter(x=>riskKind(x.risk)==='bad').length}</div></div><div class="om-card"><div class="om-card-label">Profile</div><div class="om-card-value info">${esc(M.profile)}</div></div></div><div class="om-store-grid">${list.map(storeCard).join('')||'<div class="muted">No catalog entries matched.</div>'}</div></div></div>`}
function storeCard(s){const k=riskKind(s.risk);const d=decision(s.id);const enabled=d&&d.enabled;const configured=!!d;return `<article class="om-store-card"><div><h3>${esc(s.name)}</h3><div class="om-store-desc">${esc(s.notes)}</div></div><div class="om-store-meta">${tag(s.risk,k)}${tag(s.source,'info')}${enabled?tag('Enabled','ok'):configured?tag('Configured','warn'):tag('Cataloged','info')}</div><div class="om-store-meta">${s.profiles.slice(0,4).map(p=>tag(p,'info')).join('')||tag('general','info')} ${tag((s.tools||0)+' tools','ok')}</div><div class="om-flow"><div class="om-flow-step active">Review</div><div class="om-flow-step ${configured?'active':''}">Policy Diff</div><div class="om-flow-step ${configured?'active':''}">Dry Run</div><div class="om-flow-step ${enabled?'active':''}">Enable</div></div><div class="om-actions" style="margin-top:auto"><button class="om-btn primary" onclick="toast('Review: ${esc(s.name)}')">Review</button><button class="om-btn" onclick="toast('Policy diff will use existing catalog diff endpoint')">Policy Diff</button><button class="om-btn ${k==='bad'?'danger':''}" onclick="toast('${k==='bad'?'High-risk enablement requires approval':'Configure URL before enablement'}')">${enabled?'Manage':'Enable'}</button></div></article>`}
function renderExecution(){const p=M.policy||{};$('matrix-content').innerHTML=`<div class="om-grid cols-3"><div class="om-card"><div class="om-card-label">Tool paths</div><div class="om-card-value">${Object.keys(p.tool_paths||{}).length}</div></div><div class="om-card"><div class="om-card-label">Profiles</div><div class="om-card-value info">${Object.keys(p.execution_profiles||{}).length}</div></div><div class="om-card"><div class="om-card-label">Default</div><div class="om-card-value">${esc(p.default_execution_profile||'-')}</div></div></div><div class="om-panel"><div class="om-panel-head"><span>Execution Boundary</span><button class="om-btn" onclick="location.href='/admin'">Classic execution</button></div><table class="om-table"><thead><tr><th>Tool</th><th>Executable</th></tr></thead><tbody>${Object.entries(p.tool_paths||{}).map(([a,b])=>`<tr><td>${esc(a)}</td><td class="mono">${esc(b)}</td></tr>`).join('')||'<tr><td colspan="2" class="muted">No tool paths configured.</td></tr>'}</tbody></table></div>`}
function renderAudit(){const ev=events().slice().reverse();$('matrix-content').innerHTML=`<div class="om-panel"><div class="om-panel-head"><span>Live Audit Tape</span><button class="om-btn" onclick="loadMatrix()">Refresh</button></div><div class="om-panel-body">${ev.map(e=>{const d=String(e.decision||'info').toUpperCase();const k=d.includes('DENY')?'bad':d.includes('ALLOW')?'ok':'info';return `<div class="om-audit-row"><span>${esc(fmtTime(e.timestamp))}</span><span>${tag(d,k)}</span><span>${esc(e.action||e.tool||'-')}</span><span class="summary">${esc(e.summary||e.path||'-')}</span><span>${esc(e.duration_ms?e.duration_ms+'ms':'')}</span></div>`}).join('')||'<div class="muted">No audit events loaded.</div>'}</div></div>`}
function renderDiagnostics(){const rt=M.runtime||{},c=checks();$('matrix-content').innerHTML=`<div class="om-grid cols-4"><div class="om-card"><div class="om-card-label">Runtime</div><div class="om-card-value ${rt.ok?'ok':'warn'}">${rt.ok?'Ready':'Check'}</div></div><div class="om-card"><div class="om-card-label">Checks</div><div class="om-card-value">${c.filter(x=>x.ok).length}/${c.length}</div></div><div class="om-card"><div class="om-card-label">Generated</div><div class="om-card-value" style="font-size:14px">${esc(rt.generated_at||'-')}</div></div><div class="om-card"><div class="om-card-label">Profile</div><div class="om-card-value info">${esc(M.profile)}</div></div></div><div class="om-panel"><div class="om-panel-head"><span>Doctor Checks</span></div><table class="om-table"><thead><tr><th>Check</th><th>Status</th><th>Detail</th></tr></thead><tbody>${c.map(x=>`<tr><td>${esc(x.name||x.check||'-')}</td><td>${tag(x.ok?'OK':'Warn',x.ok?'ok':'warn')}</td><td>${esc(x.detail||x.message||'')}</td></tr>`).join('')||'<tr><td colspan="3" class="muted">No doctor checks returned.</td></tr>'}</tbody></table></div>`}
function renderContext(){const ev=events();const last=[...ev].reverse().find(e=>String(e.decision||e.summary||'').toLowerCase().includes('deny'));const p=M.policy||{};$('matrix-context').innerHTML=`<h2>Live Context</h2><div class="om-context-block"><div class="om-context-title">Last denied action</div>${last?`${tag('Denied','bad')}<div class="mono truncate" style="margin-top:8px">${esc(last.action||last.tool||'-')}</div><div class="muted truncate">${esc(last.summary||last.path||'policy decision')}</div>`:'<div class="muted">No denial in loaded sample.</div>'}</div><div class="om-context-block"><div class="om-context-title">System info</div><div class="om-kv"><div>Admin Bind</div><div>${esc(p.admin_bind||'127.0.0.1:18769')}</div><div>MCP Bind</div><div>${esc(p.mcp_bind||'127.0.0.1:18770')}</div><div>Roots</div><div>${esc(roots().length)}</div><div>Profile</div><div>${esc(M.profile)}</div></div></div><div class="om-context-block"><div class="om-context-title">View model</div><div class="muted">Enterprise Classic remains at <code>/admin</code>. Operator Matrix is additive and profile-driven.</div></div>`}
loadMatrix().catch(e=>{$('matrix-content').innerHTML='<div class="om-loading">Failed to load Operator Matrix: '+esc(e.message)+'</div>';context()});
